### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by yahengqi** [yalaudah/facies_classification_benchmark#14]
Traceback (most recent call last):
  File "patch_train.py", line 373, in <module>
    train(args)
  File "patch_train.py", line 177, in train
    for i, (images, labels) in enumerate(trainloader):
  File "D:\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "D:\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "D:\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "D:\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
PS D:\dz_yalaudah\facies_classification_benchmark-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by yahengqi** [comment]
carried out  ''python patch_train.py --batch_size 32 --aug True'' error
