### ISSUE TITLE
Problem with TensorboadX add_image writer

### ISSUE THREAD

**Issue by akshitac8** [yalaudah/facies_classification_benchmark#2]
I am getting an error of KeyError: ((1, 1, 99), '|u1') with TypeError: Cannot handle this data type.
More specific error:
```
Epoch [1/101] training Loss: 1.8266
Traceback (most recent call last):
  File "/home/akshita/anaconda2/envs/Faster_RCNN/lib/python3.6/site-packages/PIL/Image.py", line 2460, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 99), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "patch_train.py", line 365, in <module>
    train(args)
  File "patch_train.py", line 204, in train
    writer.add_image('train/original_label',correct_label_decoded, epoch + 1)
  File "/home/akshita/anaconda2/envs/Faster_RCNN/lib/python3.6/site-packages/tensorboardX/writer.py", line 412, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step, walltime)
  File "/home/akshita/anaconda2/envs/Faster_RCNN/lib/python3.6/site-packages/tensorboardX/summary.py", line 205, in image
    image = make_image(tensor, rescale=rescale)
  File "/home/akshita/anaconda2/envs/Faster_RCNN/lib/python3.6/site-packages/tensorboardX/summary.py", line 243, in make_image
    image = Image.fromarray(tensor)
  File "/home/akshita/anaconda2/envs/Faster_RCNN/lib/python3.6/site-packages/PIL/Image.py", line 2463, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type``
```
I have tried the code on torch 0.4.1 and 1.0

**Comment by yalaudah** [comment]
Hi @akshitac8, can you specify what lead to this error? Did you just run `patch_train.py` and got this error message, or have you made any modifications to the code that caused this?

**Comment by akshitac8** [comment]
yes, I just ran ```patch_train.py```.

**Comment by yalaudah** [comment]
Thanks for bringing this up @akshitac8, I've fixed the issue for both `train_patch.py` and `train_section.py`. Can you pull the new changes and let me know if everything works on your end?

**Comment by akshitac8** [comment]
Thank you @yalaudah the code now works. But it works for pytorch 1.0.0 as in pytorch 0.4.1 there is no reduction term in cross entropy loss.

**Comment by akshitac8** [comment]
Also, It would be great if you share the steps for processing the Netherlands F3 data. As I wish to use the code on other seismic publicly available datasets.
Thank you in advance :slightly_smiling_face:

**Comment by yalaudah** [comment]
That's great @akshitac8, I will close the issue. Yes, ideally you would use PyTorch 1.0 with the code. 

As for the processing steps, we have talked about the steps we used on the raw F3 data to generate out model in our paper (currently under review -- but you can access the preprint on ArXiv). Best of luck with your work!
